### ISSUE TITLE
First and Last Name Blank in custom profile after registration

### ISSUE THREAD

**Issue by bill-curran** [leegarner-glfusion/profile#8]
Two points - After succesful registration, the Full Name is set correctly by combining the first and last names. The First name still defaults to Anonymous at registration which will cause a lot of problems with my older pensioners accessing the site. 

When a user or admin goes back in to his/her custom profile to make an update, the First and Last Names are blank.

Tested with latest 1.20 pull yesterday.

**Comment by leegarner** [comment]
I see the problems:
1. There's a record in the profile data for Anonymous that gets used when the user profile is read. Anonymous data is no longer saved but this record will still appear if it was saved previously. This will be deleted in 1.2.1 and the data will no longer be read if the user is anonymous.
2. There's an access check when saving profile data, and since the current user isn't fully created at that point the access check fails. 1.2.1 will have a check to allow data to be saved during registration regardless of per-field permission settings.
